```         
```

## MGE Analysis File

```{r}
library (ggplot2)
library(RColorBrewer)
library(dplyr)
library(tidyr)
library(stringr)
library(ggpubr)
library(vegan)
library(plotly)
library(ggfortify)
library(compositions)
library(ggrepel)
library(reshape2)
library(patchwork)
library(ggsignif)
```

## Including Analysis

#### Load Pertinent Files

```{r}
metadata <- read.csv("metadata.csv", header = TRUE)
metaxa_data <- read.delim("metaxa_genus.txt", header = TRUE)
MGE_data <- read.delim("MGE_genemat.txt", header = TRUE)
MGE_lengths <- read.delim("MGE_lengths.txt", header = TRUE)
```

#### Merging Metadata and Normalizing Counts using Metaxa

```{r}

long_metaxa <- metaxa_data %>%
  pivot_longer(cols = -Taxa, names_to = "SampleID", values_to = "Count")

# Merge Metaxa data with metadata
combined_metaxa <- merge(long_metaxa, metadata, by = "SampleID", all.x = TRUE)
combined_length <- merge (MGE_data, MGE_lengths, by = "GENE", all.x = TRUE)

ssu_counts <- combined_metaxa %>%
  group_by(SampleID) %>%
  summarize(SSU_Counts = sum(Count))

rownames(combined_length) <- combined_length$GENE

combined_length <- combined_length %>% select(-GENE)

MGE_length_norm <- combined_length[, 1:(ncol(combined_length)-1)]  / combined_length$length

MGE_length_norm <- MGE_length_norm[ , order(names(MGE_length_norm))]


# Normalization with Metaxa2 SSU counts
MGE_length_norm_t <- t(MGE_length_norm)
ssu_counts <- ssu_counts %>% select(-SampleID)
MGE_length_norm_t <- sweep(MGE_length_norm_t, 1, t(ssu_counts), FUN = "/")
MGE_length_SSU_norm <- t(MGE_length_norm_t) * 1540

row.names(MGE_length_SSU_norm)

normalized_MGE_data <- as.data.frame(MGE_length_SSU_norm) %>%
  mutate(GENE = rownames(MGE_length_SSU_norm)) %>%
  select(GENE, everything())

long_MGE <- normalized_MGE_data %>%
  pivot_longer(cols = -GENE, names_to = "SampleID", values_to = "Count")

combined_data <- merge(long_MGE,metadata, by = "SampleID", all.x = TRUE)
print(combined_data)


MGE_df <- combined_data %>%
  pivot_wider(names_from = GENE, values_from = Count)

print(MGE_df)


```

## Plots

### Final Plot
```{r}
cgh_data <- combined_data %>% filter(hospital == "C")
ust_data <- combined_data %>% filter(hospital == "B")
SLMC_data <- combined_data %>% filter(hospital == "A")

get_top_genes <- function(data, n = 10) {
  data %>%
    group_by(SampleID) %>%
    summarise(TotalCount = sum(Count, na.rm = TRUE)) %>%
    right_join(data, by = "SampleID") %>%
    mutate(Percentage = (Count / TotalCount) * 100) %>%
    group_by(GENE) %>%
    summarise(AverageAbundance = mean(Percentage, na.rm = TRUE)) %>%
    arrange(desc(AverageAbundance)) %>%
    top_n(n, AverageAbundance) %>%
    pull(GENE)
}

top_genes_cgh <- get_top_genes(cgh_data)
top_genes_ust <- get_top_genes(ust_data)
top_genes_slmc <- get_top_genes(SLMC_data)


create_plot_genes <- function(data, top_genes, hospital_name) {
  total_counts_per_sample <- data %>%
    group_by(SampleID) %>%
    summarise(TotalCount = sum(Count, na.rm = TRUE))
  
  data <- data %>%
    left_join(total_counts_per_sample, by = "SampleID") %>%
    mutate(Percentage = (Count / TotalCount) * 100)
  
  gene_viz <- data %>%
    mutate(GENE = ifelse(GENE %in% top_genes, GENE, "Others"))
  
  gene_viz$GENE <- factor(gene_viz$GENE, levels = c("Others", setdiff(unique(gene_viz$GENE), "Others")))
  
  num_genes <- length(levels(gene_viz$GENE))
  spectral_colors <- colorRampPalette(brewer.pal(11, "Spectral"))(num_genes)

  color_mapping <- setNames(spectral_colors, levels(gene_viz$GENE))
  color_mapping["Others"] <- "#D2B48C"
  

  ggplot(gene_viz, aes(x = SampleID, y = Percentage, fill = GENE)) +
    geom_bar(stat = "identity", position = "stack", width = 0.7) +
    scale_fill_manual(values = color_mapping) +
    labs(
      title = paste(hospital_name),
      x = "Sample", y = "Relative Abundance (%)"
    ) +
    theme_light() +
    theme(
      axis.text.x = element_text(size = 14, angle = 0, hjust = 0.5),
      axis.text.y = element_text(size = 16),
      axis.title.x = element_text(size = 18),                       
      axis.title.y = element_text(size = 18),  
      plot.title = element_text(size = 20, face = "bold"),
      legend.title = element_blank(),
      legend.text = element_text(size = 14),
      aspect.ratio = 1
    )
}


p_cgh <- create_plot_genes(cgh_data, top_genes_cgh, "C")
p_ust <- create_plot_genes(ust_data, top_genes_ust, "B")
p_slmc <- create_plot_genes(SLMC_data, top_genes_slmc, "A")


ggsave(filename = "MGE_GENE_C.png", plot = p_cgh, width = 6, height = 6, dpi = 300)
ggsave(filename = "MGE_GENE_B.png", plot = p_ust, width = 6, height = 6, dpi = 300)
ggsave(filename = "MGE_GENE_A.png", plot = p_slmc, width = 6, height = 6, dpi = 300)

print(p_cgh) 
print(p_ust)
print(p_slmc)

```


## PCA Plot

#### Without Loadings

```{r}

selected_data <- MGE_df %>% select(c(16:ncol(MGE_df)))

selected_data <- clr(selected_data)

# Perform PCA using RDA (vegan package)
pca_result <- rda(selected_data)

pca_scores <- scores(pca_result, display = "sites")
pca_data <- as.data.frame(pca_scores)

pca_data$hospital <- factor(MGE_df$hospital)
pca_data$SampleID <- MGE_df$SampleID
pca_data$month <- MGE_df$month

variance_explained <- pca_result$CA$eig / sum(pca_result$CA$eig) * 100

pc1_label <- paste("PC1 (", formatC(variance_explained[1], format = "f", digits = 2), "%)", sep="")
pc2_label <- paste("PC2 (", formatC(variance_explained[2], format = "f", digits = 2), "%)", sep="")

p <- ggplot(pca_data, aes(x = PC1, y = PC2, label = SampleID, group = hospital)) +
  geom_point(aes(color = hospital), size = 4, alpha = 0.8) + 
  geom_text(vjust = 1.5, hjust = 1.5, size = 6) +  
  stat_ellipse(level = 0.95, linetype = 2, aes(color = hospital), size = 1) +
  scale_color_manual(values = c("#D4070F", "#1C1AAF", "#c68e17")) +
  labs(x = pc1_label, y = pc2_label) +
  theme_minimal()+
  theme(text = element_text(family = "Palatino"),
        legend.title = element_blank(),
        legend.text = element_text(size = 26),
        legend.key.size = unit(1, 'cm'),
        legend.position = c(0.15, 0.9),
        legend.background = element_rect(color = "#ffffff"),
        legend.direction = "horizontal",
        axis.text.x = element_text(size = 26, angle = 0, hjust = 0.5),
        axis.text.y = element_text(size = 26),
        axis.title.x = element_text(size = 26),                       
        axis.title.y = element_text(size = 26),  
        plot.margin = unit(c(1, 1, 1, 1), "cm"))

ggsave(filename = "Pca_mge.jpg",
       width = 16, height = 13, dpi = 300, units = "in", device = 'jpg', scale = 1)
```
#### With Loadings
```{r}
# Select the data for PCA
selected_data <- MGE_df %>% select(c(16:ncol(MGE_df)))

clr_data <- clr(selected_data)


pca_result <- rda(clr_data)

pca_scores <- scores(pca_result, display = "sites")
scores_df <- as.data.frame(pca_scores)  

pca_loadings <- scores(pca_result, display = "species")
loadings_df <- as.data.frame(pca_loadings)
loadings_df$Variable <- rownames(loadings_df)

scores_df$hospital <- factor(MGE_df$hospital)
scores_df$SampleID <- MGE_df$SampleID
scores_df$month <- MGE_df$month

# Optional: Filter the loadings to display only the top contributing genes
# top_loadings <- loadings_df %>%
#   mutate(PC1_contribution = abs(PC1),
#          PC2_contribution = abs(PC2)) %>%
#   arrange(desc(PC1_contribution + PC2_contribution)) %>%
#   head(30)

variance_explained <- pca_result$CA$eig / sum(pca_result$CA$eig) * 100

pc1_label <- paste("PC1 (", formatC(variance_explained[1], format = "f", digits = 2), "%)", sep="")
pc2_label <- paste("PC2 (", formatC(variance_explained[2], format = "f", digits = 2), "%)", sep="")

combined_plot <- ggplot() +
  geom_point(data = scores_df, aes(x = PC1, y = PC2, color = hospital), size = 4, alpha = 0.8) +
  geom_text_repel(data = scores_df, aes(x = PC1, y = PC2, label = SampleID), size = 7, alpha = 0.8, max.overlaps = 100) +
  geom_segment(data = top_loadings, aes(x = 0, y = 0, xend = PC1, yend = PC2), 
               arrow = arrow(length = unit(0.1, "cm")), color = "grey", size = 0.5, alpha = 0.5) +
  geom_label_repel(data = top_loadings, aes(x = PC1, y = PC2, label = Variable), color = "black", size = 8, alpha = 0.7, max.overlaps = 100, box.padding = 0.5) +
  stat_ellipse(data = scores_df, aes(x = PC1, y = PC2, color = hospital), level = 0.95, linetype = 2, size = 1) +
  theme_minimal() +
   labs(x = pc1_label, y = pc2_label) +
  theme(text = element_text(family = "Palatino"),
        axis.title = element_text(size = 24, face = "bold"),
        legend.title = element_blank(),
        legend.text = element_text(size = 24),
        legend.key.size = unit(1, 'cm'),
        legend.position = c(0.15, 0.9),
        legend.background = element_rect(color = "#CECECE"),
        legend.direction = "horizontal",
        axis.text.x = element_text(size = 26, angle = 0, hjust = 0.5),
        axis.text.y = element_text(size = 26),
        axis.title.x = element_text(size = 26),                       
        axis.title.y = element_text(size = 26),  
        aspect.ratio = 1) +
  scale_color_manual(values = c("#D4070F", "#1C1AAF", "#c68e17"))

ggsave(filename = "MGE_pca_WithLoading.jpg",
       plot = combined_plot,
       width = 16, height = 13, dpi = 300, units = "in", device = 'jpg', scale = 1)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

## Diversity Plot

### Shannon Index

```{r}
gene_matrix <- MGE_df %>% select(c(16:ncol(MGE_df)))

gene_matrix[is.na(gene_matrix)] <- 0


# Calculate Shannon diversity
shannon_diversity <- diversity(gene_matrix, index = "shannon")


shannon_results <- data.frame(
  SampleID = MGE_df$SampleID[!duplicated(MGE_df$SampleID)], 
  Shannon = shannon_diversity
)

shannon_results <- merge(shannon_results, metadata, by = "SampleID", all.x = TRUE)
print (shannon_results)

# Perform the Kruskal-Wallis Test to check for significant differences between hospitals
kw_test_results <- kruskal.test(Shannon ~ hospital, data = shannon_results)
print(kw_test_results)
# Pairwise Wilcoxon Test with Benjamini-Hochberg adjustment for multiple comparisons
pw_wilcox_test_results <- pairwise.wilcox.test(shannon_results$Shannon, shannon_results$hospital, p.adjust.method = "BH")
print (pw_wilcox_test_results)


p <- ggplot(shannon_results, aes(x = hospital, y = Shannon, fill = hospital)) +
  geom_boxplot(alpha = 0.8, outlier.shape = NA) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', position = position_dodge(0.8), dotsize = 0.6) + 
  geom_text_repel(aes(label = SampleID), 
                  position = position_dodge(0.75), 
                  box.padding = 1,  
                  point.padding = 0.5,  
                  force = 1,
                  size = 10,
                  max.overlaps = 10, segment.color = NA) +  
  labs(x = "Hospital", 
       y = "Shannon Index") +
  theme_minimal() +
  theme(
    legend.position = "right", 
    legend.title = element_blank(), 
    axis.text.x = element_text(angle = 0, hjust = 1, size = 20),
    axis.text.y = element_text(size = 24),
    axis.title.x = element_text(size = 24, angle = 0), 
    axis.title.y = element_text(size = 24),
    legend.text = element_text(size = 24),
    plot.title = element_text(size = 18, hjust = 0.5))+
  scale_fill_manual(values = c("A" = "#89CFF0", "B" = "#fdfd96", "C" = "#ff6961"))

print(p)


ggsave(filename = "Shannon_MGEs.jpg",
       plot = p,
       width = 16, height = 13, dpi = 300, units = "in", device = 'jpg', scale = 1)
```

```{r}

signif_pairs <- data.frame(
  group1 = rep(rownames(pw_wilcox_test_results$p.value), each = ncol(pw_wilcox_test_results$p.value)),
  group2 = rep(colnames(pw_wilcox_test_results$p.value), nrow(pw_wilcox_test_results$p.value)),
  p.adj = as.vector(pw_wilcox_test_results$p.value)
) %>%
  filter(p.adj < 0.05)

max_shannon <- max(shannon_results$Shannon, na.rm = TRUE)
sig_levels <- seq(from = max_shannon + 0.04, by = 0.05, length.out = 3)

p <- ggplot(shannon_results, aes(x = hospital, y = Shannon, fill = hospital)) +
  geom_boxplot(alpha = 0.8, outlier.shape = NA) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', position = position_dodge(0.8), dotsize = 0.6) + 
  geom_text_repel(aes(label = SampleID), 
                  position = position_dodge(0.75), 
                  box.padding = 1,  
                  point.padding = 0.5,  
                  force = 1,
                  size = 10,
                  max.overlaps = 10, segment.color = NA) +  
  labs(x = "Hospital", 
       y = "Shannon Index") +
  theme_minimal() +
  theme(
    legend.position = "right", 
    legend.title = element_blank(), 
    axis.text.x = element_text(angle = 0, hjust = 1, size = 28),
    axis.text.y = element_text(size = 28),
    axis.title.x = element_text(size = 28, angle = 0), 
    axis.title.y = element_text(size = 28),
    legend.text = element_text(size = 28),
    plot.title = element_text(size = 18, hjust = 0.5))+
  scale_fill_manual(values = c("A" = "#89CFF0", "B" = "#fdfd96", "C" = "#ff6961"))
p <- p + geom_signif(
    comparisons = list(c("A", "B"), c("A", "C"), c("B", "C")),
    map_signif_level = TRUE,
    y_position = sig_levels,
    textsize = 10,
    vjust = 0
  )

print(p)

ggsave(filename = "Shannon_MGEs_WithSignif.jpg",
       plot = p,
       width = 16, height = 13, dpi = 300, units = "in", device = 'jpg', scale = 1)

```


### Evenness

```{r}
gene_matrix <- MGE_df %>% select(c(16:ncol(MGE_df)))

gene_matrix[is.na(gene_matrix)] <- 0

shannon_diversity <- diversity(gene_matrix, index = "shannon")
species_richness <- specnumber(gene_matrix)

pielou_evenness <- shannon_diversity / log(species_richness)

evenness_results <- data.frame(
  SampleID = MGE_df$SampleID[!duplicated(MGE_df$SampleID)],
  evenness = pielou_evenness
)

evenness_results <- merge(evenness_results, metadata, by = "SampleID", all.x = TRUE)

print (evenness_results)

# Perform the Kruskal-Wallis Test to check for significant differences between hospitals
kw_test_results_evenness <- kruskal.test(evenness ~ hospital, data = evenness_results)

# Pairwise Wilcoxon Test with Benjamini-Hochberg adjustment for multiple comparisons
pw_wilcox_test_results_evenness <- pairwise.wilcox.test(evenness_results$evenness, evenness_results$hospital, p.adjust.method = "BH")

print(kw_test_results_evenness)
print(pw_wilcox_test_results_evenness)

p <- ggplot(evenness_results, aes(x = hospital, y = evenness, fill = hospital)) +
  geom_boxplot(alpha = 0.8, outlier.shape = NA) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', position = position_dodge(0.8), dotsize = 0.6) + 
  geom_text_repel(aes(label = SampleID), 
                  position = position_dodge(0.75), 
                  box.padding = 1,  
                  point.padding = 0.5,  
                  force = 1,
                  size = 8,
                  max.overlaps = 10, segment.color = NA) + 
  labs(x = "Hospital", 
       y = "Evenness Index") +
  theme_minimal() +
  theme(
    legend.position = "right", 
    legend.title = element_blank(), 
    axis.text.x = element_text(angle = 0, hjust = 1, size = 20),
    axis.text.y = element_text(size = 24),
    axis.title.x = element_text(size = 24),
    axis.title.y = element_text(size = 24),
    legend.text = element_text(size = 24), 
    plot.title = element_text(size = 18, hjust = 0.5)  
  ) +
  scale_fill_manual(values = c("A" = "#89CFF0", "B" = "#fdfd96", "C" = "#ff6961"))

print(p_evenness)

ggsave(filename = "Evenness_MGEs.jpg",
       plot = p_evenness,
       width = 16, height = 13, dpi = 300, units = "in", device = 'jpg', scale = 1)

```

```{r}
# Extract significant pairs
signif_pairs <- data.frame(
  group1 = rep(rownames(pw_wilcox_test_results$p.value), each = ncol(pw_wilcox_test_results$p.value)),
  group2 = rep(colnames(pw_wilcox_test_results$p.value), nrow(pw_wilcox_test_results$p.value)),
  p.adj = as.vector(pw_wilcox_test_results$p.value)
) %>%
  filter(p.adj < 0.05)

max_evenness <- max(evenness_results$evenness, na.rm = TRUE)
sig_levels <- seq(from = max_evenness + 0.005, by = 0.005, length.out = 3)



p <- ggplot(evenness_results, aes(x = hospital, y = evenness, fill = hospital)) +
  geom_boxplot(alpha = 0.8, outlier.shape = NA) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', position = position_dodge(0.8), dotsize = 0.6) + 
  geom_text_repel(aes(label = SampleID), 
                  position = position_dodge(0.75), 
                  box.padding = 1,  
                  point.padding = 0.5,  
                  force = 1,
                  size = 10,
                  max.overlaps = 10, segment.color = NA) + 
  labs(x = "Hospital", 
       y = "Evenness Index") +
  theme_minimal() +
  theme(
    legend.position = "right", 
    legend.title = element_blank(), 
    axis.text.x = element_text(angle = 0, hjust = 1, size = 28),
    axis.text.y = element_text(size = 28),
    axis.title.x = element_text(size = 28),
    axis.title.y = element_text(size = 28),
    legend.text = element_text(size = 28), 
    plot.title = element_text(size = 18, hjust = 0.5)  
  ) +
  scale_fill_manual(values = c("A" = "#89CFF0", "B" = "#fdfd96", "C" = "#ff6961"))

p <- p + geom_signif(
    comparisons = list(c("A", "B"), c("A", "C"), c("B", "C")),
    map_signif_level = TRUE,
    y_position = sig_levels,  
    textsize = 10,
    vjust = -0.5)


print(p)


ggsave(filename = "Evenness_MGE_WithSignif.jpg",
       plot = p,
       width = 16, height = 13, dpi = 300, units = "in", device = 'jpg', scale = 1)

```

### Richness

```{r}
gene_matrix <- MGE_df %>% select(c(16:ncol(MGE_df)))
gene_matrix[is.na(gene_matrix)] <- 0
gene_richness <- specnumber(gene_matrix)

richness_results <- data.frame(
  SampleID =  MGE_df$SampleID[!duplicated(MGE_df$SampleID)], 
  richness = gene_richness
)

richness_results <- merge(richness_results, metadata, by = "SampleID", all.x = TRUE)
print (richness_results)

# Perform the Kruskal-Wallis Test to check for significant differences between hospitals
kw_test_results_richness <- kruskal.test(richness ~ hospital, data = richness_results)

# Pairwise Wilcoxon Test with Benjamini-Hochberg adjustment for multiple comparisons
pw_wilcox_test_results_richness <- pairwise.wilcox.test(richness_results$richness, richness_results$hospital, p.adjust.method = "BH")

print(kw_test_results_richness)
print(pw_wilcox_test_results_richness)


p <- ggplot(richness_results, aes(x = hospital, y = richness, fill = hospital)) +
  geom_boxplot(alpha = 0.8, outlier.shape = NA) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', position = position_dodge(0.8), dotsize = 0.6) + 
  geom_text_repel(aes(label = SampleID), position = position_dodge(0.8), size = 8) + 
  labs(x = "Hospital", 
       y = "Richness") +
  theme_minimal() +
  theme(
    legend.position = "right", 
    legend.title = element_blank(), 
    axis.text.x = element_text(angle = 0, hjust = 1, size = 20),
    axis.text.y = element_text(size = 24), 
    axis.title.x = element_text(size = 24), 
    axis.title.y = element_text(size = 24),
    legend.text = element_text(size = 24),
    plot.title = element_text(size = 18, hjust = 0.5)  
  )+
  scale_fill_manual(values = c("A" = "#89CFF0", "B" = "#fdfd96", "C" = "#ff6961"))


print(p)

ggsave(filename = "Richness_MGEs.jpg",
       plot = p,
       width = 16, height = 13, dpi = 300, units = "in", device = 'jpg', scale = 1) 
```

```{r}
# Extract significant pairs
signif_pairs <- data.frame(
  group1 = rep(rownames(pw_wilcox_test_results$p.value), each = ncol(pw_wilcox_test_results$p.value)),
  group2 = rep(colnames(pw_wilcox_test_results$p.value), nrow(pw_wilcox_test_results$p.value)),
  p.adj = as.vector(pw_wilcox_test_results$p.value)
) %>%
  filter(p.adj < 0.05)

max_richness <- max(richness_results$richness, na.rm = TRUE)
sig_levels <- seq(from = max_richness + 20 , by = 20, length.out = 3)

p <- ggplot(richness_results, aes(x = hospital, y = richness, fill = hospital)) +
  geom_boxplot(alpha = 0.8, outlier.shape = NA) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', position = position_dodge(0.8), dotsize = 0.6) + 
  geom_text_repel(aes(label = SampleID), 
                  position = position_dodge(0.75), 
                  box.padding = 1,  
                  point.padding = 0.5,  
                  force = 1,
                  size = 10,
                  max.overlaps = 10, segment.color = NA) +
  labs(x = "Hospital", 
       y = "Richness") +
  theme_minimal() +
  theme(
    legend.position = "right", 
    legend.title = element_blank(), 
    axis.text.x = element_text(angle = 0, hjust = 1, size = 28),
    axis.text.y = element_text(size = 28),
    axis.title.x = element_text(size = 28),
    axis.title.y = element_text(size = 28),
    legend.text = element_text(size = 28),
    plot.title = element_text(size = 18, hjust = 0.5)  
  )+
  scale_fill_manual(values = c("A" = "#89CFF0", "B" = "#fdfd96", "C" = "#ff6961"))

  
p <- p + geom_signif(
    comparisons = list(c("A", "B"), c("A", "C"), c("B", "C")),
    map_signif_level = TRUE,
    y_position = sig_levels,
    textsize = 10,
    vjust = 0
  )

print(p)

ggsave(filename = "Richness_MGEs_WithSignif.jpg",
       plot = p,
       width = 16, height = 13, dpi = 300, units = "in", device = 'jpg', scale = 1)
```