# Taxonomic Analysis

```{r, libraries}

library (ggplot2)
library(RColorBrewer)
library(dplyr)
library(tidyr)
library(stringr)
library(ggpubr)
library(vegan)
library(plotly)
library(ggfortify)
library(compositions)
library(pheatmap)
library(ggrepel)
library(patchwork)
```

### Load Metadata

```{r, warning=FALSE, error=FALSE, message=FALSE, results='hide', fig.show='hide'}
metadata <- read.csv("metadata.csv", header = TRUE)

```
#### Pre-processing (Only for Kraken)
```{r}
# Uncomment if using kraken 
taxonomic_data <- read.delim("merged_metakraken_abundance_table.txt", header = TRUE)
colnames(taxonomic_data) <- gsub("__profile", "", colnames(taxonomic_data))

```

#### Pre-processing (Only for Metaphlan)

```{r}
# Uncomment if using metaphlan
taxonomic_data <- read.delim("merged_abundance_table.txt", header = TRUE)
colnames(taxonomic_data)[colnames(taxonomic_data) == "clade_name"] <- "ID"

```
```{r}
long_taxonomic <- taxonomic_data %>%
pivot_longer(cols = -ID, names_to = "SampleID", values_to = "RelativeAbundance")


combined_data <- merge(long_taxonomic, metadata, by = "SampleID", all.x = TRUE)

wide_taxonomic <- combined_data %>%
  pivot_wider(names_from = ID, values_from = RelativeAbundance)

head(wide_taxonomic)
combined_data$Taxonomic_Level <- sapply(strsplit(as.character(combined_data$ID), "\\|"), function(x) length(x))

get_taxonomic_label <- function(name) {
  parts <- unlist(strsplit(name, "\\|"))
  
  switch(length(parts),
         "1" = "Kingdom",
         "2" = "Phylum",
         "3" = "Class",
         "4" = "Order",
         "5" = "Family",
         "6" = "Genus",
         "7" = "Species",
         "Other")
}

combined_data$Taxonomic_Label <- sapply(combined_data$ID, get_taxonomic_label)

extract_ID <- function(name) {
  parts <- unlist(strsplit(name, "\\|"))
  last_part <- parts[length(parts)]
  ID <- sub(".*__", "", last_part)
  return(ID)
}

combined_data$ID <- sapply(combined_data$ID, extract_ID)

combined_data <- combined_data[!is.na(combined_data$Taxonomic_Label) & combined_data$Taxonomic_Label != "Other", ]

all_taxonomic_data <- combined_data

list_of_data_frames <- combined_data %>%
  split(.$Taxonomic_Label)

kingdom_data <- list_of_data_frames$Kingdom
phylum_data <- list_of_data_frames$Phylum
class_data <- list_of_data_frames$Class
order_data <- list_of_data_frames$Order
family_data <- list_of_data_frames$Family
genus_data <- list_of_data_frames$Genus
species_data <- list_of_data_frames$Species

wide_genus_data <- genus_data %>%
  pivot_wider(names_from = ID, values_from = RelativeAbundance)


tail(genus_data)
```

## Relative abundances of Taxa

## PCA Plot

```{r}

selected_data <- wide_genus_data%>% select(c(18: ncol(wide_genus_data)))
selected_data <- clr(selected_data)
pca_result <- rda(selected_data)

pca_scores <- scores(pca_result, display = "sites")
pca_data <- as.data.frame(pca_scores)

pca_data$hospital <- wide_genus_data$hospital
pca_data$SampleID <- wide_genus_data$SampleID
pca_data$month <- wide_genus_data$month

head(pca_data$PC1)

variance_explained <- pca_result$CA$eig / sum(pca_result$CA$eig) * 100

# Names for the first two principal components including their variance explained
pc1_label <- paste("PC1 (", formatC(variance_explained[1], format = "f", digits = 2), "%)", sep="")
pc2_label <- paste("PC2 (", formatC(variance_explained[2], format = "f", digits = 2), "%)", sep="")

# Update your ggplot code for PCA
p <- ggplot(pca_data, aes(x = PC1, y = PC2, label = SampleID, group = hospital)) +
  geom_point(aes(color = hospital), size = 4, alpha = 0.8) + 
  geom_text(vjust = 1.5, hjust = 1.5, size = 8) +  
  stat_ellipse(level = 0.95, linetype = 2, aes(color = hospital), size = 1) +
  scale_color_manual(values = c("#D4070F", "#1C1AAF", "#c68e17")) +
  labs(x = pc1_label, y = pc2_label) +
  theme_minimal()+
  theme(text = element_text(family = "Palatino"),
        legend.title = element_blank(),
        legend.text = element_text(size = 26),
        legend.key.size = unit(1, 'cm'),
        legend.position = c(0.15, 0.9),
        legend.background = element_rect(color = "#CECECE"),
        legend.direction = "horizontal",
        axis.text.x = element_text(size = 26, angle = 0, hjust = 0.5),
        axis.text.y = element_text(size = 26),
        axis.title.x = element_text(size = 26),                       
        axis.title.y = element_text(size = 26),  
        plot.margin = unit(c(1, 1, 1, 1), "cm"))



# Save the plot
ggsave(filename = "Taxonomic_PCA_Genus.jpg",
       width = 16, height = 13, dpi = 300, units = "in", device = 'jpg', scale = 1)
```

```{r}

# Select the data for PCA

# top_genus <- genus_data %>%
#   group_by(ID) %>%
#   summarise(AverageAbundance = median(RelativeAbundance, na.rm = TRUE)) %>%
#   arrange(desc(AverageAbundance)) %>%
#   top_n(20, AverageAbundance) %>%
#   pull(ID)

selected_data <- wide_genus_data%>% select(c(18: ncol(wide_genus_data)))


clr_data <- clr(selected_data)


# Perform PCA using RDA (vegan package)
pca_result <- rda(clr_data)

# Extract PCA scores for the samples (sites)
pca_scores <- scores(pca_result, display = "sites")
scores_df <- as.data.frame(pca_scores)  # Convert to data frame


pca_loadings <- scores(pca_result, display = "species")

filtered_loadings <- pca_loadings[rownames(pca_loadings) %in% top_genus, ]


loadings_df <- as.data.frame(filtered_loadings)
loadings_df$Variable <- rownames(loadings_df)


scores_df$hospital <- factor(wide_genus_data$hospital)
scores_df$SampleID <- wide_genus_data$SampleID
scores_df$month <- wide_genus_data$month

# Optional: Filter the loadings to display only the top contributing genes
# top_loadings <- loadings_df %>%
#   mutate(PC1_contribution = abs(PC1),
#          PC2_contribution = abs(PC2)) %>%
#   arrange(desc(PC1_contribution + PC2_contribution)) %>%
#   head(30)


variance_explained <- pca_result$CA$eig / sum(pca_result$CA$eig) * 100

pc1_label <- paste("PC1 (", formatC(variance_explained[1], format = "f", digits = 2), "%)", sep="")
pc2_label <- paste("PC2 (", formatC(variance_explained[2], format = "f", digits = 2), "%)", sep="")


combined_plot <- ggplot() +
  geom_point(data = scores_df, aes(x = PC1, y = PC2, color = hospital), size = 4, alpha = 0.8) +
  geom_text_repel(data = scores_df, aes(x = PC1, y = PC2, label = SampleID), size = 7, alpha = 0.8, max.overlaps = 100) +
  geom_segment(data = top_loadings, aes(x = 0, y = 0, xend = PC1, yend = PC2), 
               arrow = arrow(length = unit(0.1, "cm")), color = "grey", size = 0.5, alpha = 0.5) +
  geom_label_repel(data = top_loadings, aes(x = PC1, y = PC2, label = Variable), color = "black", size = 8, alpha = 0.7, max.overlaps = 100, box.padding = 0.5) +
  stat_ellipse(data = scores_df, aes(x = PC1, y = PC2, color = hospital), level = 0.95, linetype = 2, size = 1) +
  theme_minimal() +
  labs(x = pc1_label, y = pc2_label) +
  theme(text = element_text(family = "Palatino"),
        axis.title = element_text(size = 24, face = "bold"),
        legend.title = element_blank(),
        legend.text = element_text(size = 24),
        legend.key.size = unit(1, 'cm'),
        legend.position = c(0.15, 0.9),
        legend.background = element_rect(color = "#CECECE"),
        legend.direction = "horizontal",
        axis.text.x = element_text(size = 26, angle = 0, hjust = 0.5),
        axis.text.y = element_text(size = 26),
        axis.title.x = element_text(size = 26),                       
        axis.title.y = element_text(size = 26),  
        aspect.ratio = 1) +
  scale_color_manual(values = c("#D4070F", "#1C1AAF", "#c68e17"))

# Save the plot
ggsave(filename = "Taxonomic_withPCA_Loading.jpg",
       plot = combined_plot,
       width = 16, height = 13, dpi = 300, units = "in", device = 'jpg', scale = 1)
```

## Relative Abundance

#### Genus

```{r}
c_data <- genus_data %>% filter(hospital == "C")
b_data <- genus_data %>% filter(hospital == "B")
a_data <- genus_data %>% filter(hospital == "A")

get_top_genera <- function(data, n = 10) {
  data %>%
    group_by(SampleID) %>%
    summarise(TotalAbundance = sum(RelativeAbundance, na.rm = TRUE)) %>%
    right_join(data, by = "SampleID") %>%
    group_by(ID) %>%
    summarise(AverageAbundance = mean(RelativeAbundance, na.rm = TRUE)) %>%
    arrange(desc(AverageAbundance)) %>%
    top_n(n, AverageAbundance) %>%
    pull(ID)
}

# Extract top genera for each hospital
top_genera_c <- get_top_genera(c_data)
top_genera_b <- get_top_genera(b_data)
top_genera_a <- get_top_genera(a_data)


create_plot_genera <- function(data, top_genera, hospital_name) {
  
  genera_viz <- data %>%
    mutate(ID = ifelse(ID %in% top_genera, ID, "Others"))
  
  
  genera_viz$ID <- factor(genera_viz$ID, levels = c("Others", setdiff(unique(genera_viz$ID), "Others")))
  
  
  num_genera <- length(levels(genera_viz$ID))
  spectral_colors <- colorRampPalette(brewer.pal(11, "Spectral"))(num_genera)
  
  
  color_mapping <- setNames(spectral_colors, levels(genera_viz$ID))
  color_mapping["Others"] <- "#D2B48C"
  
  
  ggplot(genera_viz, aes(x = SampleID, y = RelativeAbundance, fill = ID)) +
    geom_bar(stat = "identity", position = "stack", width = 0.7) +
    scale_fill_manual(values = color_mapping) +
    labs(
      title = paste(hospital_name),
      x = "Sample", y = "Relative Abundance (%)"
    ) +
    theme_light() +
    theme(
      axis.text.x = element_text(size = 16, angle = 0, hjust = 0.5),
      axis.text.y = element_text(size = 16),
      axis.title.x = element_text(size = 18),                       
      axis.title.y = element_text(size = 18),  
      plot.title = element_text(size = 20, face = "bold"),
      legend.title = element_blank(),
      legend.text = element_text(size = 14, face = "italic"),
      aspect.ratio = 1 
    )
}

p_c_g <- create_plot_genera(c_data, top_genera_c, "C")
p_b_g <- create_plot_genera(b_data, top_genera_b, "B")
p_a_g <- create_plot_genera(a_data, top_genera_a, "A")

ggsave(filename = "Relative_Abundance_C.png", plot = p_c_g, width = 6, height = 6, dpi = 300)
ggsave(filename = "Relative_Abundance_B.png", plot = p_b_g, width = 6, height = 6, dpi = 300)
ggsave(filename = "Relative_Abundance_A.png", plot = p_a_g, width = 6, height = 6, dpi = 300)

print(p_c_g)
print(p_b_g)
print(p_a_g)
```
#### Phylum

```{r}
c_data <- phylum_data %>% filter(hospital == "C")
b_data <- phylum_data %>% filter(hospital == "B")
a_data <- phylum_data %>% filter(hospital == "A")

get_top_phyla <- function(data, n = 10) {
  data %>%
    group_by(SampleID) %>%
    summarise(TotalAbundance = sum(RelativeAbundance, na.rm = TRUE)) %>%
    right_join(data, by = "SampleID") %>%
    group_by(ID) %>%
    summarise(AverageAbundance = mean(RelativeAbundance, na.rm = TRUE)) %>%
    arrange(desc(AverageAbundance)) %>%
    top_n(n, AverageAbundance) %>%
    pull(ID)
}

# Extract top phyla for each hospital
top_phyla_c <- get_top_phyla(c_data)
top_phyla_b <- get_top_phyla(b_data)
top_phyla_a <- get_top_phyla(a_data)


create_plot_phyla <- function(data, top_phyla, hospital_name) {
  
  phyla_viz <- data %>%
    mutate(ID = ifelse(ID %in% top_phyla, ID, "Others"))
  
  
  phyla_viz$ID <- factor(phyla_viz$ID, levels = c("Others", setdiff(unique(phyla_viz$ID), "Others")))
  
  
  num_phyla <- length(levels(phyla_viz$ID))
  spectral_colors <- colorRampPalette(brewer.pal(11, "Spectral"))(num_phyla)
  
  
  color_mapping <- setNames(spectral_colors, levels(phyla_viz$ID))
  color_mapping["Others"] <- "#D2B48C"
  
  
  ggplot(phyla_viz, aes(x = SampleID, y = RelativeAbundance, fill = ID)) +
    geom_bar(stat = "identity", position = "stack", width = 0.7) +
    scale_fill_manual(values = color_mapping) +
    labs(
      title = paste(hospital_name),
      x = "Sample", y = "Relative Abundance (%)"
    ) +
    theme_light() +
    theme(
      axis.text.x = element_text(size = 16, angle = 0, hjust = 0.5),
      axis.text.y = element_text(size = 16),
      axis.title.x = element_text(size = 18),                       
      axis.title.y = element_text(size = 18),  
      plot.title = element_text(size = 20, face = "bold"),
      legend.title = element_blank(),
      legend.text = element_text(size = 14, face = "italic"),
      aspect.ratio = 1 
    )
}

p_c_ph <- create_plot_phyla(c_data, top_phyla_c, "C")
p_b_ph <- create_plot_phyla(b_data, top_phyla_b, "B")
p_a_ph <- create_plot_phyla(a_data, top_phyla_a, "A")

ggsave(filename = "Relative_Abundance_c_phyla.png", plot = p_c_ph, width = 6, height = 6, dpi = 300)
ggsave(filename = "Relative_Abundance_b_phyla.png", plot = p_b_ph, width = 6, height = 6, dpi = 300)
ggsave(filename = "Relative_Abundance_a_phyla.png", plot = p_a_ph, width = 6, height = 6, dpi = 300)

print(p_c_ph)  
print(p_b_ph)
print(p_a_ph)
```
## Diversity

### Shannon

```{r}


genus_matrix <- genus_data %>%
  pivot_wider(names_from = ID, values_from = RelativeAbundance, values_fill = list(RelativeAbundance = 0)) %>%
  select(-SampleID, -alias, -month, -name, -hospital, -replicate, -HWW, -hospital_description, -no_of_beds, -lat, -long,
         -sample_material, -DNA_ng_ml, -A260.280, -plot_name, -Taxonomic_Level, -Taxonomic_Label) %>%
  as.matrix()


shannon_diversity <- diversity(genus_matrix, index = "shannon")

shannon_results <- data.frame(
  SampleID = genus_data$SampleID[!duplicated(genus_data$SampleID)], 
  Shannon = shannon_diversity
)

shannon_results <- merge(shannon_results, metadata, by = "SampleID", all.x = TRUE)
print (shannon_results)

# Perform the Kruskal-Wallis Test to check for significant differences between hospitals
kw_test_results <- kruskal.test(Shannon ~ hospital, data = shannon_results)
print(kw_test_results)
# Pairwise Wilcoxon Test with Benjamini-Hochberg adjustment for multiple comparisons
pw_wilcox_test_results <- pairwise.wilcox.test(shannon_results$Shannon, shannon_results$hospital, p.adjust.method = "BH")
print (pw_wilcox_test_results)

p <- ggplot(shannon_results, aes(x = hospital, y = Shannon, fill = hospital)) +
  geom_boxplot(alpha = 0.8, outlier.shape = NA) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', position = position_dodge(0.8), dotsize = 0.6) + 
  geom_text_repel(aes(label = SampleID), 
                  position = position_dodge(0.75), 
                  box.padding = 1,  
                  point.padding = 0.5,  
                  force = 1,
                  size = 8,
                  max.overlaps = 10, segment.color = NA)+  
  labs(x = "Hospital", 
       y = "Shannon Index") +
  theme_minimal() +
  theme(
    legend.position = "right", 
    legend.title = element_blank(), 
    axis.text.x = element_text(angle = 0, hjust = 1, size = 28),
    axis.text.y = element_text(size = 28),
    axis.title.x = element_text(size = 28, angle = 0), 
    axis.title.y = element_text(size = 28),
    legend.text = element_text(size = 28),
    plot.title = element_text(size = 18, hjust = 0.5))+
  scale_fill_manual(values = c("A" = "#89CFF0", "B" = "#fdfd96", "C" = "#ff6961"))


print(p)

# Save the plot
ggsave(filename = "Shannon_genus.jpg",
       plot = p,
       width = 16, height = 13, dpi = 300, units = "in", device = 'jpg', scale = 1)
```

```{r}
# Extract significant pairs
signif_pairs <- data.frame(
  group1 = rep(rownames(pw_wilcox_test_results$p.value), each = ncol(pw_wilcox_test_results$p.value)),
  group2 = rep(colnames(pw_wilcox_test_results$p.value), nrow(pw_wilcox_test_results$p.value)),
  p.adj = as.vector(pw_wilcox_test_results$p.value)
) %>%
  filter(p.adj < 0.05)

max_shannon <- max(shannon_results$Shannon, na.rm = TRUE)
sig_levels <- seq(from = max_shannon + 0.1, by = 0.1, length.out = 3)


p <- ggplot(shannon_results, aes(x = hospital, y = Shannon, fill = hospital)) +
  geom_boxplot(alpha = 0.8, outlier.shape = NA) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', position = position_dodge(0.8), dotsize = 0.6) + 
  geom_text_repel(aes(label = SampleID), 
                  position = position_dodge(0.75), 
                  box.padding = 1,  
                  point.padding = 0.5,  
                  force = 1,
                  size = 10,
                  max.overlaps = 10, segment.color = NA) +  
  labs(x = "Hospital", 
       y = "Shannon Index") +
  theme_minimal() +
  theme(
    legend.position = "right", 
    legend.title = element_blank(), 
    axis.text.x = element_text(angle = 0, hjust = 1, size = 28),
    axis.text.y = element_text(size = 28),
    axis.title.x = element_text(size = 28, angle = 0), 
    axis.title.y = element_text(size = 28),
    legend.text = element_text(size = 28),
    plot.title = element_text(size = 18, hjust = 0.5))+
  scale_fill_manual(values = c("A" = "#89CFF0", "B" = "#fdfd96", "C" = "#ff6961"))
p <- p + geom_signif(
    comparisons = list(c("A", "B"), c("A", "C"), c("B", "C")),
    map_signif_level = TRUE,
    y_position = sig_levels,
    textsize = 10,
    vjust = 0
  )

ggsave(filename = "Shannon_Genus_WithSig.jpg",
       plot = p,
       width = 16, height = 13, dpi = 300, units = "in", device = 'jpg', scale = 1)


```

### Evenness

```{r}

genus_matrix <- genus_data %>%
  pivot_wider(names_from = ID, values_from = RelativeAbundance, values_fill = list(RelativeAbundance = 0)) %>%
  select(-SampleID, -alias, -month, -name, -hospital, -replicate, -HWW, -hospital_description, -no_of_beds, -lat, -long,
         -sample_material, -DNA_ng_ml, -A260.280, -plot_name, -Taxonomic_Level, -Taxonomic_Label) %>%
  as.matrix()


shannon_diversity <- diversity(genus_matrix, index = "shannon")
species_richness <- specnumber(genus_matrix)


pielou_evenness <- shannon_diversity / log(species_richness)


evenness_results <- data.frame(
  SampleID = genus_data$SampleID[!duplicated(genus_data$SampleID)],  
  evenness = pielou_evenness
)

evenness_results <- merge(evenness_results, metadata, by = "SampleID", all.x = TRUE)

print (evenness_results)


# Perform the Kruskal-Wallis Test to check for significant differences between hospitals
kw_test_results_evenness <- kruskal.test(evenness ~ hospital, data = evenness_results)

# Pairwise Wilcoxon Test with Benjamini-Hochberg adjustment for multiple comparisons
pw_wilcox_test_results_evenness <- pairwise.wilcox.test(evenness_results$evenness, evenness_results$hospital, p.adjust.method = "BH")

print(kw_test_results_evenness)
print(pw_wilcox_test_results_evenness)

p <- ggplot(evenness_results, aes(x = hospital, y = evenness, fill = hospital)) +
  geom_boxplot(alpha = 0.8, outlier.shape = NA) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', position = position_dodge(0.8), dotsize = 0.6) + 
  geom_text_repel(aes(label = SampleID), 
                  position = position_dodge(0.75), 
                  box.padding = 1,  
                  point.padding = 0.5,  
                  force = 1,
                  size = 10,
                  max.overlaps = 10, segment.color = NA) + 
  labs(x = "Hospital", 
       y = "Evenness Index") +
  theme_minimal() +
  theme(
    legend.position = "right", 
    legend.title = element_blank(), 
    axis.text.x = element_text(angle = 0, hjust = 1, size = 20),
    axis.text.y = element_text(size = 24),
    axis.title.x = element_text(size = 24),
    axis.title.y = element_text(size = 24),
    legend.text = element_text(size = 24), 
    plot.title = element_text(size = 18, hjust = 0.5)  
  ) +
  scale_fill_manual(values = c("A" = "#89CFF0", "B" = "#fdfd96", "C" = "#ff6961"))

# Save the plot
ggsave(filename = "Evenness_genus.jpg",
       plot = p,
       width = 16, height = 13, dpi = 300, units = "in", device = 'jpg', scale = 1)
```

```{r}
# Extract significant pairs
signif_pairs <- data.frame(
  group1 = rep(rownames(pw_wilcox_test_results$p.value), each = ncol(pw_wilcox_test_results$p.value)),
  group2 = rep(colnames(pw_wilcox_test_results$p.value), nrow(pw_wilcox_test_results$p.value)),
  p.adj = as.vector(pw_wilcox_test_results$p.value)
) %>%
  filter(p.adj < 0.05)

max_evenness <- max(evenness_results$evenness, na.rm = TRUE)
sig_levels <- seq(from = max_evenness + 0.03, by = 0.03, length.out = 3)


p <- ggplot(evenness_results, aes(x = hospital, y = evenness, fill = hospital)) +
  geom_boxplot(alpha = 0.8, outlier.shape = NA) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', position = position_dodge(0.8), dotsize = 0.6) + 
  geom_text_repel(aes(label = SampleID), 
                  position = position_dodge(0.75), 
                  box.padding = 1,  
                  point.padding = 0.5,  
                  force = 1,
                  size = 10,
                  max.overlaps = 10, segment.color = NA) + 
  labs(x = "Hospital", 
       y = "Evenness Index") +
  theme_minimal() +
  theme(
    legend.position = "right", 
    legend.title = element_blank(), 
    axis.text.x = element_text(angle = 0, hjust = 1, size = 28),
    axis.text.y = element_text(size = 28),
    axis.title.x = element_text(size = 28),
    axis.title.y = element_text(size = 28),
    legend.text = element_text(size = 28), 
    plot.title = element_text(size = 18, hjust = 0.5)  
  ) +
  scale_fill_manual(values = c("A" = "#89CFF0", "B" = "#fdfd96", "C" = "#ff6961"))

p <- p + geom_signif(
    comparisons = list(c("A", "B"), c("A", "C"), c("B", "C")),
    map_signif_level = TRUE,
    y_position = sig_levels,
    textsize = 10,
    vjust = -0.5
  )

print(p)

# Save the plot
ggsave(filename = "Evenness_Genus_WithSig.jpg",
       plot = p,
       width = 16, height = 13, dpi = 300, units = "in", device = 'jpg', scale = 1)
```

### Richness

```{r}

genus_matrix <- genus_data %>%
  pivot_wider(names_from = ID, values_from = RelativeAbundance, values_fill = list(RelativeAbundance = 0)) %>%
  select(-SampleID, -alias, -month, -name, -hospital, -replicate, -HWW, -hospital_description, -no_of_beds, -lat, -long,
         -sample_material, -DNA_ng_ml, -A260.280, -plot_name, -Taxonomic_Level, -Taxonomic_Label) %>%
  as.matrix()

genus_richness <- specnumber(genus_matrix)

richness_results <- data.frame(
  SampleID = genus_data$SampleID[!duplicated(genus_data$SampleID)], 
  richness = genus_richness
)


richness_results <- merge(richness_results, metadata, by = "SampleID", all.x = TRUE)
print (richness_results)

# Perform the Kruskal-Wallis Test to check for significant differences between hospitals
kw_test_results_richness <- kruskal.test(richness ~ hospital, data = richness_results)

# Pairwise Wilcoxon Test with Benjamini-Hochberg adjustment for multiple comparisons
pw_wilcox_test_results_richness <- pairwise.wilcox.test(richness_results$richness, richness_results$hospital, p.adjust.method = "BH")

print(kw_test_results_richness)
print(pw_wilcox_test_results_richness)


p_richness<- ggplot(richness_results, aes(x = hospital, y = richness, fill = hospital)) +
  geom_boxplot(alpha = 0.8, outlier.shape = NA) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', position = position_dodge(0.8), dotsize = 0.6) + 
  geom_text_repel(aes(label = SampleID), position = position_dodge(0.8), size = 8) + 
  labs(x = "Hospital", 
       y = "Richness") +
  theme_minimal() +
  theme(
    legend.position = "right", 
    legend.title = element_blank(), 
    axis.text.x = element_text(angle = 0, hjust = 1, size = 20),  
    axis.title.x = element_text(size = 24),
    axis.title.y = element_text(size = 24),
    legend.text = element_text(size = 24),
    plot.title = element_text(size = 18, hjust = 0.5)  
  )+
  scale_fill_manual(values = c("A" = "#89CFF0", "B" = "#fdfd96", "C" = "#ff6961"))

print(p_richness)

# Save the plot
ggsave(filename = "Richness_genus.jpg",
       plot = p_richness,
       width = 16, height = 13, dpi = 300, units = "in", device = 'jpg', scale = 1)
```

```{r}
signif_pairs <- data.frame(
  group1 = rep(rownames(pw_wilcox_test_results$p.value), each = ncol(pw_wilcox_test_results$p.value)),
  group2 = rep(colnames(pw_wilcox_test_results$p.value), nrow(pw_wilcox_test_results$p.value)),
  p.adj = as.vector(pw_wilcox_test_results$p.value)
) %>%
  filter(p.adj < 0.05)

max_richness <- max(richness_results$richness, na.rm = TRUE)
sig_levels <- seq(from = max_richness + 15 , by = 15, length.out = 3)

p <- ggplot(richness_results, aes(x = hospital, y = richness, fill = hospital)) +
  geom_boxplot(alpha = 0.8, outlier.shape = NA) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', position = position_dodge(0.8), dotsize = 0.6) + 
  geom_text_repel(aes(label = SampleID), 
                  position = position_dodge(0.75), 
                  box.padding = 1,  
                  point.padding = 0.5,  
                  force = 1,
                  size = 10,
                  max.overlaps = 10, segment.color = NA) + 
  labs(x = "Hospital", 
       y = "Richness") +
  theme_minimal() +
  theme(
    legend.position = "right", 
    legend.title = element_blank(), 
    axis.text.x = element_text(angle = 0, hjust = 1, size = 28),
    axis.text.y = element_text(size = 28),
    axis.title.x = element_text(size = 28),
    axis.title.y = element_text(size = 28),
    legend.text = element_text(size = 28),
    plot.title = element_text(size = 18, hjust = 0.5)  
  )+
  scale_fill_manual(values = c("A" = "#89CFF0", "B" = "#fdfd96", "C" = "#ff6961"))

  
p <- p + geom_signif(
    comparisons = list(c("A", "B"), c("A", "C"), c("B", "C")),
    map_signif_level = TRUE,
    y_position = sig_levels,
    textsize = 10,
    vjust = 0
  )
print(p)
# Save the plot
ggsave(filename = "Richness_Genus_WithSig.jpg",
       plot = p,
       width = 16, height = 13, dpi = 300, units = "in", device = 'jpg', scale = 1)
```
